version: '2'
services:
  db:
    image: mdillon/postgis:9.5
  web:
    build: .
    working_dir: /code
    command: ./docker-entrypoint.sh
    volumes:
      - ../respa_config:/srv/django_local_settings.d
    ports:
      - "8000:8000"
    depends_on:
      - db
